# Setup
title: 새로운 알고리즘 블로그 (여기 클릭)
tagline: Python with Coreenee
url: "https://deveryday.github.io/"
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: JUNSUNG KIM
  url: https://coreenee.github.io
  email: kkim509@naver.com

# Custom vars
version: 3.0.0
github:
  repo: https://github.com/Coreenee/coreenee.github.io
